# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-southeast-1"

  default_tags {
    tags = { "Environment" : "dev", "ManagedBy" : "Terragrunt", "Project" : "glasnost" }
  }
}
