# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "C:/Users/Noppasin Sritongkul/Desktop/GIT/private/glasnost/terraform/environments/dev/vpc/terraform.tfstate"
  }
}
