# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state-3001bd9d"
    encrypt = true
    key     = "environments/dev/vpc/terraform.tfstate"
    region  = "ap-southeast-1"
  }
}
